import type { Metadata } from 'next';
import InsightArticle from '@/components/InsightArticle';

export const metadata: Metadata = {
  title: "Google Ads Campaign Types: Which Format Fits Your Business Goal? | R.K Digital Media",
  description: "Search, Performance Max, Shopping, Display, Video and Demand Gen are not interchangeable. The right choice starts with the customer journey and the data you can provide.",
  openGraph: { title: "Google Ads Campaign Types: Which Format Fits Your Business Goal?", description: "Search, Performance Max, Shopping, Display, Video and Demand Gen are not interchangeable. The right choice starts with the customer journey and the data you can provide.", type: 'article', locale: 'en_IN', url: "https://rkdigitalmedia.in/insights/google-ads-campaign-types", siteName: 'R.K Digital Media' },
  alternates: { canonical: "https://rkdigitalmedia.in/insights/google-ads-campaign-types" },
};
const articleSchema = {
  '@context':'https://schema.org','@type':'Article',headline:"Google Ads Campaign Types: Which Format Fits Your Business Goal?",description:"Search, Performance Max, Shopping, Display, Video and Demand Gen are not interchangeable. The right choice starts with the customer journey and the data you can provide.",
  url:"https://rkdigitalmedia.in/insights/google-ads-campaign-types",dateModified:'2026-10-01',
  author:{'@type':'Person',name:'Rohit Kumar'},publisher:{'@type':'Organization',name:'R.K Digital Media',url:'https://rkdigitalmedia.in'}
};
export default function PostPage(){
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><InsightArticle category="GOOGLE ADS" title="Google Ads Campaign Types: Which Format Fits Your Business Goal?" intro="Search, Performance Max, Shopping, Display, Video and Demand Gen are not interchangeable. The right choice starts with the customer journey and the data you can provide." readTime="10 min" updated="October 1, 2026" toc={["Search campaigns","Performance Max","Shopping","Display","Video and Demand Gen","How to choose","Common mistakes"]} sections={[{"label":"HIGH INTENT","title":"Search campaigns","paragraphs":["Search is useful when people already express intent through queries. Performance depends on query quality, ad relevance and the landing experience."]},{"label":"AUTOMATION","title":"Performance Max","paragraphs":["Performance Max can access multiple Google inventory surfaces and uses automation to find conversions. It works best when conversion tracking and creative or product inputs are strong."]},{"label":"PRODUCTS","title":"Shopping","paragraphs":["Shopping is built around product information and is particularly relevant to ecommerce. Feed quality, product data, pricing, availability and landing-page consistency matter."]},{"label":"DISCOVERY","title":"Display","paragraphs":["Display can support awareness, remarketing and specific audience strategies. Evaluate it on that objective rather than expecting it to behave like high-intent search."]},{"label":"VIDEO","title":"Video and Demand Gen","paragraphs":["Video and Demand Gen can support awareness, consideration and remarketing. Creative quality and audience strategy become especially important."]},{"label":"DECISION","title":"How to choose","paragraphs":["Start with the customer journey: active search demand, product comparison, awareness, remarketing or visual discovery. Choose the format whose inventory and controls match that job."]},{"label":"MISTAKES","title":"Common mistakes","paragraphs":["Launching every campaign type at once, using one landing page for unrelated intent, tracking low-value actions as conversions and judging campaigns before meaningful data exists are common sources of confusion."]}]} /></>;
}