import type { Metadata } from 'next';
import InsightArticle from '@/components/InsightArticle';
import InsightVisual from '@/components/InsightVisual';

export const metadata: Metadata = {
  title: "Google Ads Expert in Delhi: How to Evaluate a PPC Service Before Hiring | R.K Digital Media",
  description: "A practical buyer's guide to evaluating Google Ads management: strategy, tracking, search terms, landing pages, communication and the numbers that matter.",
  openGraph: { title: "Google Ads Expert in Delhi: How to Evaluate a PPC Service Before Hiring", description: "A practical buyer's guide to evaluating Google Ads management: strategy, tracking, search terms, landing pages, communication and the numbers that matter.", type: 'article', locale: 'en_IN', url: "https://rkdigitalmedia.in/insights/google-ads-expert-delhi", siteName: 'R.K Digital Media' },
  alternates: { canonical: "https://rkdigitalmedia.in/insights/google-ads-expert-delhi" },
};
const articleSchema = {
  '@context':'https://schema.org','@type':'Article',headline:"Google Ads Expert in Delhi: How to Evaluate a PPC Service Before Hiring",description:"A practical buyer's guide to evaluating Google Ads management: strategy, tracking, search terms, landing pages, communication and the numbers that matter.",
  url:"https://rkdigitalmedia.in/insights/google-ads-expert-delhi",dateModified:'2026-10-01',
  author:{'@type':'Person',name:'Rohit Kumar'},publisher:{'@type':'Organization',name:'R.K Digital Media',url:'https://rkdigitalmedia.in'}
};
export default function PostPage(){
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><InsightArticle category="GOOGLE ADS" title="Google Ads Expert in Delhi: How to Evaluate a PPC Service Before Hiring" intro="A practical buyer's guide to evaluating Google Ads management: strategy, tracking, search terms, landing pages, communication and the numbers that matter." readTime="10 min" updated="October 1, 2026" toc={["Start with business economics","Audit the account","Check conversion tracking","Evaluate search quality","Review landing pages","Ask better reporting questions"]} sections={[{"label":"ECONOMICS","title":"Start with business economics",visual:<InsightVisual kind="expert"/>, "paragraphs":["Define customer value, gross margin, sales conversion rate and capacity before discussing target ROAS or cost per lead. Advertising targets should follow the business model."]},{"label":"AUDIT","title":"Audit the account","paragraphs":["Look for wasted spend, unclear objectives, duplicated targeting, weak negatives, irrelevant search terms and conversion actions that do not represent meaningful outcomes."]},{"label":"TRACKING","title":"Check conversion tracking",visual:<InsightVisual kind="expert"/>, "paragraphs":["Ask which actions count as conversions and how calls, forms, purchases and qualified leads are distinguished. Duplicate or low-value conversions can distort decisions."]},{"label":"QUALITY","title":"Evaluate search quality","paragraphs":["Search terms reveal what the market is actually asking for. A manager should show examples of useful queries, wasted queries and changes made in response."]},{"label":"LANDING PAGES","title":"Review landing pages","paragraphs":["Ask whether the destination matches the promise in the ad. Strong targeting cannot rescue a page that hides the offer or makes contact difficult."]},{"label":"REPORTING","title":"Ask better reporting questions",visual:<InsightVisual kind="expert"/>, "paragraphs":["Instead of asking only 'what was the ROAS?', ask what changed, why it changed, which leads became customers and what the next experiment is."]}]} /></>;
}