type VisualProps={kind:'channels'|'economics'|'combined'};

const Box=({x,y,w,h,title,body,accent=false}:{x:number;y:number;w:number;h:number;title:string;body:string;accent?:boolean})=><g>
  <rect x={x} y={y} width={w} height={h} rx="12" fill={accent?'rgba(232,40,43,0.10)':'#141414'} stroke={accent?'#e8282b':'#2a2a2a'}/>
  <text x={x+18} y={y+27} fill="#f0eeee" fontSize="13" fontWeight="700" fontFamily="Montserrat,Arial">{title}</text>
  <text x={x+18} y={y+49} fill="#9a9a9a" fontSize="11" fontFamily="Outfit,Arial">{body}</text>
</g>;

export default function SeoVsPaidAdsVisual({kind}:VisualProps){
  if(kind==='channels') return <div className="rounded-xl border border-[var(--rkd-border)] bg-[var(--rkd-card)] p-4 md:p-6 overflow-hidden"><div className="flex items-center justify-between mb-4"><span className="section-label">// CHANNEL MAP</span><span className="text-[10px] font-mono uppercase tracking-[0.1em] text-[var(--rkd-fg-muted)]">Two different acquisition mechanisms</span></div><svg viewBox="0 0 760 300" className="w-full h-auto" role="img" aria-label="Comparison of SEO and paid search acquisition mechanisms"><defs><marker id="arrow-channel" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#e8282b"/></marker></defs><Box x={24} y={24} w={330} h={112} title="SEO" body="Earn organic visibility over time" accent/><Box x={406} y={24} w={330} h={112} title="PAID SEARCH" body="Buy eligible ad placements while active"/><Box x={24} y={176} w={330} h={88} title="Asset building" body="Content + technical quality + relevance"/><Box x={406} y={176} w={330} h={88} title="Demand capture" body="Budget + targeting + landing page"/><path d="M189 136V168" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-channel)"/><path d="M571 136V168" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-channel)"/></svg></div>;

  if(kind==='economics') return <div className="rounded-xl border border-[var(--rkd-border)] bg-[var(--rkd-card)] p-4 md:p-6 overflow-hidden"><div className="flex items-center justify-between mb-4"><span className="section-label">// ECONOMICS CHECK</span><span className="text-[10px] font-mono uppercase tracking-[0.1em] text-[var(--rkd-fg-muted)]">Compare business outcomes, not clicks alone</span></div><svg viewBox="0 0 760 250" className="w-full h-auto" role="img" aria-label="Acquisition economics decision flow"><defs><marker id="arrow-economics" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#e8282b"/></marker></defs><Box x={18} y={68} w={150} h={100} title="Traffic" body="Clicks / visits"/><Box x={204} y={68} w={150} h={100} title="Qualified lead" body="Intent + fit"/><Box x={390} y={68} w={150} h={100} title="Sale" body="Lead-to-sale rate" accent/><Box x={576} y={68} w={166} h={100} title="Unit economics" body="Profit + lifetime value"/><path d="M168 118H198" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-economics)"/><path d="M354 118H384" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-economics)"/><path d="M540 118H570" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-economics)"/></svg></div>;

  return <div className="rounded-xl border border-[var(--rkd-border)] bg-[var(--rkd-card)] p-4 md:p-6 overflow-hidden"><div className="flex items-center justify-between mb-4"><span className="section-label">// CONNECTED SYSTEM</span><span className="text-[10px] font-mono uppercase tracking-[0.1em] text-[var(--rkd-fg-muted)]">Separate channels, shared learning</span></div><svg viewBox="0 0 760 280" className="w-full h-auto" role="img" aria-label="SEO and paid search working as connected acquisition systems"><defs><marker id="arrow-combined" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#e8282b"/></marker></defs><Box x={26} y={34} w={220} h={92} title="PAID SEARCH" body="Test demand + capture intent"/><Box x={514} y={34} w={220} h={92} title="SEO" body="Build durable organic visibility"/><Box x={257} y={154} w={246} h={92} title="SEARCH INSIGHTS" body="Queries, topics, conversion signals" accent/><path d="M246 80L330 154" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-combined)"/><path d="M514 80L430 154" stroke="#e8282b" strokeWidth="2" markerEnd="url(#arrow-combined)"/><path d="M330 154L246 126" stroke="#555" strokeWidth="1.5" strokeDasharray="5 5" markerEnd="url(#arrow-combined)"/><path d="M430 154L514 126" stroke="#555" strokeWidth="1.5" strokeDasharray="5 5" markerEnd="url(#arrow-combined)"/></svg></div>;
}
