import type { Metadata } from 'next';

const blogPosts = [
  {
    slug: 'google-ads-suspension-recovery-complete-guide',
    title: 'Google Ads Suspension Recovery: A Practical Account Review & Appeal Guide',
    excerpt: 'What to check before appealing a suspended Google Ads account, how to audit the underlying issue, and what to do after reinstatement.',
    category: 'Google Ads',
    readTime: '15 min',
    date: '2025-01-10',
    keywords: ['Google Ads suspended account recovery', 'Google Ads policy violation appeal', 'circumventing systems suspension fix', 'Google Ads reinstatement process'],
  },
  {
    slug: 'local-seo-strategy-greater-noida',
    title: 'Local SEO Strategy for Greater Noida: A Practical Framework',
    excerpt: 'A practical framework covering Google Business Profile, local search intent, reviews, citations, local content, links and measurement.',
    category: 'Local SEO',
    readTime: '18 min',
    date: '2024-12-28',
    keywords: ['local SEO Greater Noida', 'SEO services Greater Noida', 'Map Pack optimization', 'local business SEO strategy'],
  },
  {
    slug: 'ai-automation-lead-generation-5-workflows',
    title: 'AI Automation for Lead Generation: 5 Workflows Worth Automating',
    excerpt: 'Five practical workflows for capturing, qualifying and following up with leads, including where human handoff matters.',
    category: 'AI Automation',
    readTime: '14 min',
    date: '2025-01-02',
    keywords: ['AI lead generation automation', 'WhatsApp AI agent setup', 'n8n workflow templates', 'CRM automation for small business'],
  },
  {
    slug: 'seo-vs-paid-ads-2025-which-wins',
    title: 'SEO vs Paid Ads for Greater Noida Businesses: How to Choose',
    excerpt: 'Compare SEO and Google Ads using urgency, economics, search intent, lead quality and long-term acquisition value.',
    category: 'SEO Strategy',
    readTime: '12 min',
    date: '2025-01-15',
    keywords: ['SEO vs PPC Greater Noida', 'SEO or Google Ads for local business', 'organic vs paid search', 'digital marketing ROI'],
  },
  {
    slug: 'gmb-optimization-map-pack-checklist-50-steps',
    title: 'Google Business Profile Optimization Checklist: What Actually Matters',
    excerpt: 'A practical checklist for profile accuracy, categories, services, reviews, website relevance and measurement.',
    category: 'Local SEO',
    readTime: '10 min',
    date: '2024-12-05',
    keywords: ['GMB optimization checklist', 'Google Business Profile SEO', 'Map Pack ranking factors', 'local SEO Greater Noida'],
  },
  // NEW ARTICLES ADDED
  {
    slug: 'google-ads-expert-noida',
    title: 'Google Ads Expert in Noida: What a Good PPC Partner Should Actually Do',
    excerpt: 'A practical guide to evaluating Google Ads expertise: search intent, tracking, landing pages, economics and reporting.',
    category: 'Google Ads',
    readTime: '10 min',
    date: '2025-01-17',
    keywords: ['Google Ads Expert in Noida', 'Google Ads expert Noida', 'Certified Google Ads professional Noida', 'PPC expert Noida'],
  },
  {
    slug: 'google-ads-expert-delhi',
    title: 'Google Ads Expert in Delhi: How to Evaluate a PPC Service Before Hiring',
    excerpt: 'A buyer's guide to evaluating Google Ads management: strategy, tracking, search quality, landing pages and reporting.',
    category: 'Google Ads',
    readTime: '10 min',
    date: '2025-01-17',
    keywords: ['Google Ads Expert in Delhi', 'Google Ads expert Delhi', 'Certified Google Ads professional Delhi', 'PPC expert Delhi'],
  },
  {
    slug: 'google-ads-expert-greater-noida',
    title: 'Google Ads Expert in Greater Noida: A Practical Guide to Better Campaign Management',
    excerpt: 'What effective Google Ads management looks like for local and regional businesses—from search intent and geography to lead quality.',
    category: 'Google Ads',
    readTime: '10 min',
    date: '2025-01-17',
    keywords: ['Google Ads Expert in Greater Noida', 'Google Ads expert Greater Noida', 'Certified Google Ads professional Greater Noida', 'PPC expert Greater Noida'],
  },
  {
    slug: 'google-ads-campaign-types',
    title: 'Type of Google Ads Campaigns: Which One Is Right for Your Business? | R.K Digital Media',
    excerpt: 'Complete guide to types of Google Ads campaigns: Search, Display, Shopping, Video, and PMax. Statistics, pros & cons, and which campaign type works best for different business goals. Google Certified breakdown.',
    category: 'Google Ads',
    readTime: '15 min',
    date: '2025-01-17',
    keywords: ['type of Google Ads campaigns', 'Google Ads campaign types', 'Search vs Display vs Shopping Google Ads', 'Google PMax campaign'],
  },
];

export { blogPosts };