import type { Metadata } from 'next';

const blogPosts = [
  {
    slug: 'google-ads-suspension-recovery-complete-guide',
    title: 'Google Ads Suspension Recovery: A Practical Account Review & Appeal Guide',
    excerpt: 'A practical guide to diagnosing suspension reasons, reviewing account and website risks, correcting genuine issues and preparing a factual appeal.',
    category: 'Google Ads',
    readTime: '12 min',
    date: '2026-10-01',
    keywords: ['Google Ads suspended account recovery', 'Google Ads policy violation appeal', 'circumventing systems suspension fix', 'Google Ads reinstatement process'],
  },
  {
    slug: 'local-seo-strategy-greater-noida',
    title: 'Local SEO Strategy for Greater Noida: A Practical Framework',
    excerpt: 'A practical local SEO framework covering technical SEO, Google Business Profile optimisation, citations, content and location-focused search intent for Greater Noida service businesses.',
    category: 'Local SEO',
    readTime: '18 min',
    date: '2024-12-28',
    keywords: ['local SEO Greater Noida', 'SEO services Greater Noida', 'Map Pack optimization', 'local business SEO strategy'],
  },
  {
    slug: 'ai-automation-lead-generation-5-workflows',
    title: 'AI Automation for Lead Generation: 5 Workflows Worth Automating',
    excerpt: 'Five practical automation workflows covering lead capture, qualification, CRM routing, follow-up and human handoff.',
    category: 'AI Automation',
    readTime: '14 min',
    date: '2025-01-02',
    keywords: ['AI lead generation automation', 'WhatsApp AI agent setup', 'n8n workflow templates', 'CRM automation for small business'],
  },
  {
    slug: 'seo-vs-paid-ads-2025-which-wins',
    title: 'SEO vs Paid Ads for Greater Noida Businesses: How to Choose',
    excerpt: 'Compare SEO and Google Ads for local businesses using search intent, time horizon, budget, conversion tracking and business goals.',
    category: 'SEO Strategy',
    readTime: '12 min',
    date: '2025-01-15',
    keywords: ['SEO vs PPC Greater Noida', 'SEO or Google Ads for local business', 'organic vs paid search', 'digital marketing ROI'],
  },
  {
    slug: 'gmb-optimization-map-pack-checklist-50-steps',
    title: 'Google Business Profile Optimization Checklist: What Actually Matters',
    excerpt: 'A practical Google Business Profile checklist covering categories, services, reviews, photos, business information, local relevance and ongoing management.',
    category: 'Local SEO',
    readTime: '10 min',
    date: '2024-12-05',
    keywords: ['GMB optimization checklist', 'Google Business Profile SEO', 'Map Pack ranking factors', 'local SEO Greater Noida'],
  },
  // NEW ARTICLES ADDED
  {
    slug: 'google-ads-expert-noida',
    title: 'Google Ads Expert in Noida: How to Evaluate a PPC Partner | R.K Digital Media',
    excerpt: 'What to look for when evaluating Google Ads management in Noida, including account structure, conversion tracking, landing pages and optimisation.',
    category: 'Google Ads',
    readTime: '10 min',
    date: '2025-01-17',
    keywords: ['Google Ads Expert in Noida', 'Google Ads expert Noida', 'Certified Google Ads professional Noida', 'PPC expert Noida'],
  },
  {
    slug: 'google-ads-expert-delhi',
    title: 'Google Ads Expert in Delhi: How to Evaluate a PPC Partner | R.K Digital Media',
    excerpt: 'A practical guide to evaluating Google Ads management in Delhi, from campaign structure and tracking to landing pages and optimisation.',
    category: 'Google Ads',
    readTime: '10 min',
    date: '2025-01-17',
    keywords: ['Google Ads Expert in Delhi', 'Google Ads expert Delhi', 'Certified Google Ads professional Delhi', 'PPC expert Delhi'],
  },
  {
    slug: 'google-ads-expert-greater-noida',
    title: 'Google Ads Expert in Greater Noida: How to Evaluate a PPC Partner | R.K Digital Media',
    excerpt: 'A practical guide to evaluating Google Ads management in Greater Noida, including account structure, tracking, landing pages and optimisation.',
    category: 'Google Ads',
    readTime: '10 min',
    date: '2025-01-17',
    keywords: ['Google Ads Expert in Greater Noida', 'Google Ads expert Greater Noida', 'Certified Google Ads professional Greater Noida', 'PPC expert Greater Noida'],
  },

  {
    slug: 'google-ads-management-cost-india',
    title: 'Google Ads Management Cost in India: What You Actually Pay For | R.K Digital Media',
    excerpt: 'Understand Google Ads management fees in India, what an agency actually manages, how ad spend differs from management cost, and how to compare proposals without choosing on price alone.',
    category: 'Google Ads',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['Google Ads management cost India', 'Google Ads management fees India', 'Google Ads agency cost', 'PPC management pricing India'],
  },
  {
    slug: 'seo-services-cost-noida',
    title: 'SEO Services Cost in Noida: What Affects Pricing and What to Expect | R.K Digital Media',
    excerpt: 'A practical guide to SEO pricing in Noida, including technical work, content, local SEO, competition, reporting and the difference between cheap activity and meaningful search growth.',
    category: 'SEO Strategy',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['SEO services cost Noida', 'SEO pricing Noida', 'SEO company cost Noida', 'SEO packages Noida'],
  },
  {
    slug: 'how-to-choose-website-development-company-noida',
    title: 'How to Choose a Website Development Company in Noida | R.K Digital Media',
    excerpt: 'Use this practical checklist to compare website development companies in Noida across technology, SEO, performance, mobile UX, ownership, maintenance and conversion readiness.',
    category: 'Website Development',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['website development company Noida', 'website development company in Noida', 'web development company Noida', 'website developer Noida'],
  },

  {
    slug: 'google-ads-for-small-businesses',
    title: 'Google Ads for Small Businesses: A Practical Guide to Getting Started | R.K Digital Media',
    excerpt: 'Learn how small businesses can use Google Ads with focused targeting, realistic budgets, conversion tracking and a simple optimisation process.',
    category: 'Google Ads',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['Google Ads for small businesses', 'Google Ads small business India', 'PPC for small business', 'small business Google Ads'],
  },
  {
    slug: 'ppc-services-india',
    title: 'PPC Services in India: What Does a PPC Agency Actually Manage? | R.K Digital Media',
    excerpt: 'Understand what PPC services in India should cover, from campaign strategy and keyword management to conversion tracking, optimisation and reporting.',
    category: 'Google Ads',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['PPC services in India', 'PPC agency India', 'PPC management services', 'pay per click services India'],
  },
  {
    slug: 'seo-company-noida-how-to-choose',
    title: 'SEO Company in Noida: How to Choose the Right SEO Partner | R.K Digital Media',
    excerpt: 'A practical framework for comparing SEO companies in Noida based on strategy, technical SEO, content, local search, reporting and business outcomes.',
    category: 'SEO Strategy',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['SEO company in Noida', 'SEO company Noida', 'best SEO company in Noida', 'SEO agency Noida'],
  },
  {
    slug: 'website-development-cost-noida',
    title: 'Website Development Cost in Noida: What Determines the Price? | R.K Digital Media',
    excerpt: 'Understand the factors behind website development cost in Noida, including design, pages, technology, integrations, SEO, performance and ongoing support.',
    category: 'Website Development',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['website development cost Noida', 'website development price Noida', 'website cost Noida', 'web development cost Noida'],
  },
  {
    slug: 'google-business-profile-management-services',
    title: 'Google Business Profile Management Services: What Should Be Included? | R.K Digital Media',
    excerpt: 'A practical guide to what ongoing Google Business Profile management should cover, including profile optimisation, categories, services, reviews, photos, monitoring and reporting.',
    category: 'Local SEO',
    readTime: '12 min',
    date: '2026-10-07',
    keywords: ['Google Business Profile management services', 'Google Business Profile management', 'GBP management services', 'GMB management services'],
  },
  {
    slug: 'google-business-profile-optimization-services',
    title: 'Google Business Profile Optimization Services: Complete Guide | R.K Digital Media',
    excerpt: 'Learn what effective Google Business Profile optimisation services should cover, from business information and categories to reviews, photos, local relevance and measurement.',
    category: 'Local SEO',
    readTime: '13 min',
    date: '2026-10-07',
    keywords: ['Google Business Profile optimization services', 'Google Business Profile optimization', 'GBP optimization services', 'GMB optimization services'],
  },
  {
    slug: 'google-business-profile-cost-india',
    title: 'Google Business Profile Management Cost in India: What Are You Paying For? | R.K Digital Media',
    excerpt: 'Understand what affects GBP management cost in India and how to compare ongoing Google Business Profile and local SEO proposals by scope.',
    category: 'Local SEO',
    readTime: '10 min',
    date: '2026-10-07',
    keywords: ['Google Business Profile management cost India', 'GBP management cost India', 'GMB management pricing India', 'Google Business Profile services cost'],
  },

  {
    slug: 'google-ads-campaign-types',
    title: 'Google Ads Campaign Types: Which Format Fits Your Business Goal? | R.K Digital Media',
    excerpt: 'A practical breakdown of Search, Display, Shopping, Video and Performance Max campaigns and the business goals each format can support.',
    category: 'Google Ads',
    readTime: '15 min',
    date: '2025-01-17',
    keywords: ['type of Google Ads campaigns', 'Google Ads campaign types', 'Search vs Display vs Shopping Google Ads', 'Google PMax campaign'],
  },
];

export { blogPosts };